name: Release snapshot

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  release:
    if: contains(github.event.head_commit.message, '[release-snapshot]')
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Build Hurl and its components
        run: .\build.ps1
      - name: Create GitHub snapshot release
        shell: pwsh
        run: |
          $date = get-date -Format 'yyyyMMdd'
          $commitFull = '${{ github.sha }}'
          $commitShort = '${{ github.sha }}'.Substring(0, 7)
          $tag = "vSnapshot-$date-$commitShort"
          gh release create $tag './Utils/Hurl_Installer.exe' --title "snapshot-$date-$commitShort" --prerelease --generate-notes --target $commitFull
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Hurl_Installer
          path: ./Utils/Hurl_Installer.exe
